kind = "web"
previewPath = "/"
title = "Milles Tweet"
version = "1.0.0"
id = "artifacts/millestweet"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23843

[services.development]
run = "pnpm --filter @workspace/millestweet run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/millestweet", "run", "build" ]
publicDir = "artifacts/millestweet/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23843"
BASE_PATH = "/"
